import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اختر لغة تطبيق",
          "2": "عربي",
          "3": "فرنسي",
          "4": "انجليزي",
          "onBoardingTitle1": "نظام HGP",
          "onBoardingTitle2": "حلول التقسيمات الداخلية",
          "onBoardingTitle3": "التكوين المستمر",
          "onBoardingTitle4": "طلب نصيحة",
          "onBoardingDescription1":
              "هو الحل الأمثل لتطوير الزخرفة. حتى الأشياء الثقيلة أو الأحمال المجهدة بانتظام مثل قضبان الستائر أو رفوف المعاطف أو شاشات التلفزيون يمكن تعليقها دون تعزيز",
          "onBoardingDescription2":
              "شركة SPA HASNAOUI GYPSUM PANEL هي شركة تابعة لمجموعة شركات HASNAOUI المتخصصة في إنتاج ألواح الجص الليفي المقوى. تهدف هذه الألواح الصلبة ذات الألياف الزجاجية إلى تحقيق الأعمال الداخلية العمودية والفواصل والبطانات.",
          "onBoardingDescription3":
              "ندعو المصممين والمتقدمين للمشاركة في دوراتنا التدريبية والتدريبية في الموزعين المعتمدين لدينا، وغالبًا ما يتم توفير تدريبه في المواقع الرئيسية.",
          "onBoardingDescription4":
              "يتوفر مكتب HGP الفني دائمًا للمصممين والمشغلين لتقديم المساعدة في مواقع البناء وتقديم المشورة بشأن أنسب الحلول للمشاكل المحددة لكل مشروع.",
          "onBoardingtitre": "تجاوز",
          "nom": "أدخل اسمك *",
          "prenom": "أدخل اسمك الأول *",
          "adresse": "أدخل عنوانك *",
          "nom_entreprise": "أدخل اسم شركتك",
          "mail": "أدخل بريدك الإلكتروني *",
          "telephone": "أدخل رقم هاتفك *",
          "password": "أدخل كلمة السر الخاصة بك *",
          "connectez-vous": "تسجيل الدخول",
          "textone": "هل لديك حساب ؟",
          "texttwo": "تسجيل الدخول",
          "inscrire": "تسجيل",
          "email_validation1": "يجب عليك ملء بريدك",
          "email_validation2": "بريد إلكتروني غير صالح",
          "largeur_porte": "عليك أن تملأ عرض بابك",
          "hauteur_porte": "عليك أن تملأ ارتفاع بابك",
          "largeur_fenetre": "عليك أن تملأ عرض النافذة",
          "hauteur_fenetre": "يجب أن تملأ ارتفاع النافذة",
          "hauteur1": "يجب أن تملأ طولك",
          "hauteur2": "يجب أن يكون الارتفاع 6.25 م كحد أقصى",
          "largeur": "يجب أن تملأ عرضك",
          "password1": "يجب عليك ملء كلمة السر الخاصة بك",
          "password2": "لا يمكن أن تكون كلمة المرور أقل من",
          "nom_validation1": "املأ اسمك",
          "nom_validation2": "لا يمكن أن يكون الاسم أكبر من",
          "nom_validation3": "الاسم غير صالح",
          "prenom_validation1": "املأ اسمك الأول",
          "prenom_validation2": "الاسم الأول لا يمكن أن يكون أكبر من",
          "prenom_validation3": "الاسم الأول غير صالح",
          "telephone_val1": "تحتاج إلى ملء هاتفك",
          "telephone_val2": "لا يمكن أن يكون الهاتف أعلى من",
          "telephone_val3": "لا يمكن أن يكون الهاتف أقل من",
          "telephone_val4": "يجب أن يكون  هاتف رقم",
          "adresse1": "يجب أن تملأ عنوانك",
          "adresse2": "العنوان غير صالح",
          "calculer": "احسب",
          "largeur_calcul": "أدخل العرض الخاص بك *",
          "hauteur_calcul": "أدخل ارتفاعك *",
          "m": "متر",
          "mur_plein": "الحائط الصلب",
          "mur_porte": "جدار الباب",
          "mur_fenetre": "جدار نوافذ",
          "mur_porte_fenetre": "جدار به باب ونوافذ",
          "produit": "منتج",
          "slogo": "النظام \n      الأكثر عملية",
          "slogo1": "لمقدمي الطلبات الأكثر تطلبا",
          "produit1": "منتجاتنا :",
          "voir_tout": "مشاهدة كل",
          "syst": "أنظمتنا :",
          "prjc": "مشاريعنا :",
          "home": "صفحة رئيسية",
          "calcul": "حساب",
          "distributeurs": "موزعين",
          "paramètres": "إعدادات",
          "about": "معلوماتنا",
          "contact": "اتصل بنا",
          "hgp": "  حسناوي جيبسون بنل",
        },
        "fr": {
          "1": "Choisir la langue de l'application",
          "2": "Arabe",
          "3": "Français",
          "4": "Anglais",
          "onBoardingTitle1": "HGP System",
          "onBoardingTitle2": "Solutions pour Cloisons intérieures",
          "onBoardingTitle3": "Formation continue",
          "onBoardingTitle4": "Demander conseil",
          "onBoardingDescription1":
              "est la solution idéale pour faire évoluer la décoration. Même les objets lourds ou les charges régulièrement sollicitées comme les tringles à rideaux ou les porte-manteaux ou les écrans tv peuvent être accrochés sans renfort",
          "onBoardingDescription2":
              "SPA HASNAOUI GYPSUM PANEL est une filiale du GROUPE DES SOCIÉTÉS HASNAOUI spécialisée dans la production de panneaux de plâtre fibro renforcés. Ces panneaux massifs avec fibres de verre sont destinés à la réalisation d’ouvrages intérieurs verticaux, de cloisons, de doublages.",
          "onBoardingDescription3":
              "Nous invitons les concepteurs et les applicateurs à participer à nos formations itinérantes et à nos cours de formation chez nos distributeurs agrées, ses formations sont souvent assurées sur les grands chantiers.",
          "onBoardingDescription4":
              "Le bureau technique de HGP est toujours disponible pour les concepteurs el les opérateurs afin de fournir une assistance sur les chantiers de construction et de conseiller les solutions les plus appropriées sur les problèmes spécifiques de chaque projet.",
          "onBoardingtitre": "Passer",
          "nom": "Enter votre Nom *",
          "prenom": "Enter votre Prénom *",
          "adresse": "Enter votre Adresse *",
          "nom_entreprise": "Enter votre Nom entreprise",
          "mail": "Enter votre mail *",
          "telephone": "Enter votre Numéro de téléphone *",
          "password": "Enter votre Password *",
          "connectez-vous": "Connectez-vous",
          "textone": "Vous  avez un compte ?",
          "texttwo": "Connecter",
          "inscrire": "s'inscrire",
          "email_validation1": "Il faut remplir votre Mail",
          "email_validation2": "Invalid email",
          "largeur_porte": "Il faut remplir votre largeur porte",
          "hauteur_porte": "Il faut remplir votre hauteur porte",
          "largeur_fenetre": "Il faut remplir votre largeur fenetre",
          "hauteur_fenetre": "Il faut remplir votre hauteur fenetre",
          "hauteur1": "Il faut remplir votre Hauteur",
          "hauteur2": "Hauteur doit etre maximum 6,25m",
          "largeur": "Il faut remplir votre Largeur",
          "password1": "Il faut remplir votre Mot pass",
          "password2": "Mot passe ne peut être inférieure à ",
          "nom_validation1": "Il faut remplir votre Nom",
          "nom_validation2": "Le nom ne peut être supérieure à",
          "nom_validation3": "Nom n'est pas valide",
          "prenom_validation1": "Il faut remplir votre prénom",
          "prenom_validation2": "Le prénom ne peut être supérieure à",
          "prenom_validation3": "prénom n'est pas valide",
          "telephone_val1": "Il faut remplir votre telephone",
          "telephone_val2": "Le telephone ne peut être supérieure à",
          "telephone_val3": "Le telephone ne peut être inférieure à",
          "telephone_val4": "Le téléphone doit étre un nombre",
          "adresse1": "Il faut remplir votre adresse",
          "adresse2": "adresse n'est pas valide",
          "calculer": "Calculer",
          "largeur_calcul": "Enter votre Largeur *",
          "hauteur_calcul": "Enter votre Hauteur *",
          "m": "m",
          "mur_plein": "mur plein",
          "mur_porte": "mur avec porte",
          "mur_fenetre": "mur avec fenetre",
          "mur_porte_fenetre": "mur avec porte et fenetre",
          "produit": "Produit",
          "slogo": "LE SYSTEME LE \n     PLUS PRATIQUE",
          "slogo1": "POUR LES APPLICATEURS \n     LES PLUS EXIGEANTS",
          "produit1": "Nos Produits :",
          "voir_tout": "Voir tout",
          "syst": "Nos Systèmes :",
          "prjc": "Nos Projets :",
          "home": "Accueil",
          "calcul": "Calcul",
          "distributeurs": "Distributeurs",
          "paramètres": "Paramètres",
          "about": "A propres",
          "contact": "Contacter-nous",
          "hgp": "HGP "
        },
        "en": {
          "1": "Choose the language of the application",
          "2": "Arabic",
          "3": "French",
          "4": "English",
          "onBoardingTitle1": "HGP System",
          "onBoardingTitle2": "Solutions for Interior Partitions",
          "onBoardingTitle3": "Continuing education",
          "onBoardingTitle4": "seek the advice",
          "onBoardingDescription1":
              "is the ideal solution to develop the decoration. Even heavy objects or regularly stressed loads such as curtain rods or coat racks or tv screens can be hung without reinforcement",
          "onBoardingDescription2":
              "SPA HASNAOUI GYPSUM PANEL is a subsidiary of the HASNAOUI GROUP of companies specialized in the production of reinforced fibro plaster panels. These solid panels with fiberglass are intended for the realization of vertical interior works, partitions, linings.",
          "onBoardingDescription3":
              "We invite designers and applicators to participate in our itinerant training and training courses at our authorized distributors, its training is often provided on major sites.",
          "onBoardingDescription4":
              "HGP’s technical office is always available for designers and operators to provide assistance on construction sites and advise the most appropriate solutions on the specific problems of each project.",
          "onBoardingtitre": "Pass",
          "nom": "Enter your First Name *",
          "prenom": "Enter your Last Name *",
          "adresse": "Enter your Address *",
          "nom_entreprise": "Enter your Company Name",
          "mail": "Enter your email *",
          "telephone": "Enter your Phone Number *",
          "password": "Enter your Password *",
          "connectez-vous": "login",
          "textone": "Do you have an account?",
          "texttwo": "Connect",
          "inscrire": "Sign up",
          "email_validation1": "You must fill in your Mail",
          "email_validation2": "Invalid Mail",
          "largeur_porte": "You have to fill your door width",
          "hauteur_porte": "You have to fill your door height",
          "largeur_fenetre": "You have to fill your window width",
          "hauteur_fenetre": "You must fill your window height",
          "hauteur1": "You must fill your Height",
          "hauteur2": "Height must be maximum 6.25m",
          "largeur": "You must fill your Width",
          "password1": "You must fill in your password",
          "password2": "Password cannot be less than",
          "nom_validation1": "Fill in your First Name",
          "nom_validation2": "The name cannot be greater than",
          "nom_validation3": "First Name is not valid",
          "prenom_validation1": "Fill in your Last Name",
          "prenom_validation2": "The Last name cannot be greater than",
          "prenom_validation3": "Last name is not valid",
          "telephone_val1": "You need to fill out your phone",
          "telephone_val2": "The telephone cannot be higher than",
          "telephone_val3": "The telephone cannot be less than",
          "telephone_val4": "The phone must have a number",
          "adresse1": "You must fill in your address",
          "adresse2": "Address is not valid",
          "calculer": "Calculate",
          "largeur_calcul": "Enter your Width *",
          "hauteur_calcul": "Enter your Height *",
          "m": "m",
          "mur_plein": "solid wall",
          "mur_porte": "door wall",
          "mur_fenetre": "windowed wall",
          "mur_porte_fenetre": "wall with door and windows",
          "produit": "Product",
          "slogo": "THE MOST \n      PRACTICAL SYSTEM",
          "slogo1": "FOR THE MOST DEMANDING N APPLICATORS",
          "produit1": "Our Products:",
          "voir_tout": "See All",
          "syst": "Our Systems :",
          "prjc": "Our Projects:",
          "home": "Home",
          "calcul": "Calculation",
          "distributeurs": "Distributors",
          "paramètres": "Settings",
          "about": "Has own",
          "contact": "Contact-Us",
          "hgp": "HGP"
        }
      };
}
